[package]
name = "yesqlr_macros"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
yesqlr = { path = "../yesqlr"}
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
